apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "customerjwt"
spec:
  peers:
  - mtls: {}
  targets:
  - name: customer
  origins:
  - jwt:
      issuer: "http://192.168.99.105:31465/auth/realms/istio"
      jwksUri: "http://192.168.99.105:31465/auth/realms/istio/protocol/openid-connect/certs"
      audiences:
      - customer-tutorial  
  principalBinding: USE_ORIGIN
